esphome:
  name: eastron-smart-meter
  project:
    name: PVPro.Eastron-SDM630
    version: "2.0"

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
  encryption:
    key: "XXXXX"

ota:
  password: "XXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eastron-Smart-Meter"
    password: "12345678"

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  rx_pin: D1
  tx_pin: D0
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: sdm_meter
    phase_a:
      current:
        name: "SDM630 Current Phase A"
      voltage:
        name: "SDM630 Voltage Phase A"
      active_power:
        name: "SDM630 Power Phase A"
      power_factor:
        name: "SDM630 Power Factor Phase A"
#      apparent_power:
#        name: "SDM630 Apparent Power Phase A"
#      reactive_power:
#        name: "SDM630 Reactive Power Phase A"
      phase_angle:
        name: "SDM630 Phase Angle Phase A"
    phase_b:
      current:
        name: "SDM630 Current Phase B"
      voltage:
        name: "SDM630 Voltage Phase B"
      active_power:
        name: "SDM630 Power Phase B"
      power_factor:
        name: "SDM630 Power Factor Phase B"
#      apparent_power:
#        name: "SDM630 Apparent Power Phase B"
#      reactive_power:
#        name: "SDM630 Reactive Power Phase B"
      phase_angle:
        name: "SDM630 Phase Angle Phase B"
    phase_c:
      current:
        name: "SDM630 Current Phase C"
      voltage:
        name: "SDM630 Voltage Phase C"
      active_power:
        name: "SDM630 Power Phase C"
      power_factor:
        name: "SDM630 Power Factor Phase C"
#      apparent_power:
#        name: "SDM630 Apparent Power Phase C"
#      reactive_power:
#        name: "SDM630 Reactive Power Phase C"
      phase_angle:
        name: "SDM630 Phase Angle Phase C"
    frequency:
      name: "SDM630 Frequency"
    total_power:
      name: "SDM630 Total Power"
      accuracy_decimals: 3
    import_active_energy:
      name: "SDM630 Import Active Energy"
    export_active_energy:
      name: "SDM630 Export Active Energy"
#    import_reactive_energy:
#      name: "SDM630 Import Reactive Energy"
#    export_reactive_energy:
#      name: "SDM630 Export Reactive Energy"
    update_interval: 10s
  - platform: uptime
    name: "Eastron Uptime"
    update_interval: 60s
  - platform: wifi_signal
    name: "Eastron Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Eastron IP Address"
    ssid:
      name: "Eastron Wi-Fi SSID"
    bssid:
      name: "Eastron Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
